<h1>Trabalho Final Disciplina Análise de Dados com Spark</h1>
<hr>
<h5><b> Prof. André Victor </b></h5>
<h5><b> Aluno: Leandro Leite </b></h5>
<hr>

<h2>Parte 1:</h2>
<h5> Utilizar a biblioteca PySpark para realizar a mesma análise que foi feita no trabalho de Hadoop, acrescentando novas análises exploratórias mais detalhadas. </h5>

<h5> No trecho de código abaixo serão realizadas as seguintes análises:<br>
    <ul><li>Qual a quantidade total de clientes por estado?</li>
    <li>Qual o número total de sellers (vendedores) por estado?</li>
    <li>Quais são os possíveis status atribuídos a um pedido e quantos pedidos foram aprovados no ano de 2016?</li>
    <li>Quais são os cinco maiores pedidos recebidos na plataforma? Identificar o meio de pagamento, valor, cidade estado do cliente que realizou os respectivos pedidos.</li> 
    <li>Com base na resposta anterior, quais os possíveis endereços para o cliente que realizou o maior pedido na plataforma?</li></ul>

In [1]:
#Criando o dataframe com os dados dos cliente.
df_customers = spark\
  .read\
  .option("inferSchema", "true")\
  .option("header", "true")\
  .csv("/user/leandrocmleite/dataset_ecommerce/olist_customers_dataset.csv")

df_customers.show(5)

+--------------------+--------------------+------------------------+--------------------+--------------+
|         customer_id|  customer_unique_id|customer_zip_code_prefix|       customer_city|customer_state|
+--------------------+--------------------+------------------------+--------------------+--------------+
|06b8999e2fba1a1fb...|861eff4711a542e4b...|                   14409|              franca|            SP|
|18955e83d337fd6b2...|290c77bc529b7ac93...|                    9790|sao bernardo do c...|            SP|
|4e7b3e00288586ebd...|060e732b5b29e8181...|                    1151|           sao paulo|            SP|
|b2b6027bc5c5109e5...|259dac757896d24d7...|                    8775|     mogi das cruzes|            SP|
|4f2d8ab171c80ec83...|345ecd01c38d18a90...|                   13056|            campinas|            SP|
+--------------------+--------------------+------------------------+--------------------+--------------+
only showing top 5 rows

In [2]:
# Calculando a quantidade total de clientes por Estado.

df_customers.groupBy("customer_state").count().orderBy('count',ascending=False).show()

+--------------+-----+
|customer_state|count|
+--------------+-----+
|            SP|41746|
|            RJ|12852|
|            MG|11635|
|            RS| 5466|
|            PR| 5045|
|            SC| 3637|
|            BA| 3380|
|            DF| 2140|
|            ES| 2033|
|            GO| 2020|
|            PE| 1652|
|            CE| 1336|
|            PA|  975|
|            MT|  907|
|            MA|  747|
|            MS|  715|
|            PB|  536|
|            PI|  495|
|            RN|  485|
|            AL|  413|
+--------------+-----+
only showing top 20 rows

In [3]:
#Criando o dataframe com os dados dos vendedores (sellers).
df_sellers = spark\
  .read\
  .option("inferSchema", "true")\
  .option("header", "true")\
  .csv("/user/leandrocmleite/dataset_ecommerce/olist_sellers_dataset.csv")

df_sellers.show(5)

+--------------------+----------------------+-----------------+------------+
|           seller_id|seller_zip_code_prefix|      seller_city|seller_state|
+--------------------+----------------------+-----------------+------------+
|3442f8959a84dea7e...|                 13023|         campinas|          SP|
|d1b65fc7debc3361e...|                 13844|       mogi guacu|          SP|
|ce3ad9de960102d06...|                 20031|   rio de janeiro|          RJ|
|c0f3eea2e14555b6f...|                  4195|        sao paulo|          SP|
|51a04a8a6bdcb23de...|                 12914|braganca paulista|          SP|
+--------------------+----------------------+-----------------+------------+
only showing top 5 rows

In [4]:
# Calculando a quantidade total de sellers por Estado.

df_sellers.groupBy("seller_state").count().orderBy('count',ascending=False).show()

+------------+-----+
|seller_state|count|
+------------+-----+
|          SP| 1849|
|          PR|  349|
|          MG|  244|
|          SC|  190|
|          RJ|  171|
|          RS|  129|
|          GO|   40|
|          DF|   30|
|          ES|   23|
|          BA|   19|
|          CE|   13|
|          PE|    9|
|          PB|    6|
|          RN|    5|
|          MS|    5|
|          MT|    4|
|          SE|    2|
|          RO|    2|
|          PI|    1|
|          AM|    1|
+------------+-----+
only showing top 20 rows

In [5]:
#Criando o dataframe com os dados dos pedidos.
df_pedidos = spark\
  .read\
  .option("inferSchema", "true")\
  .option("header", "true")\
  .csv("/user/leandrocmleite/dataset_ecommerce/olist_orders_dataset.csv")

df_pedidos.show(5)

+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|            order_id|         customer_id|order_status|order_purchase_timestamp|  order_approved_at|order_delivered_carrier_date|order_delivered_customer_date|order_estimated_delivery_date|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|e481f51cbdc54678b...|9ef432eb625129730...|   delivered|     2017-10-02 10:56:33|2017-10-02 11:07:15|         2017-10-04 19:55:00|          2017-10-10 21:25:13|          2017-10-18 00:00:00|
|53cdb2fc8bc7dce0b...|b0830fb4747a6c6d2...|   delivered|     2018-07-24 20:41:37|2018-07-26 03:24:27|         2018-07-26 14:31:00|          2018-08-07 15:27:45|          2018-08-13 00:00:00|
|47770eb9100c2d0c4...|41ce2a54c0b03bf34...|   delivered|     2018-08-08 08:38:49|2018-08-08 08:55:23|         2018-08-08 13:50:00|          2018-08-17 18:06:29|          2018-09-04 00:00:00|
|949d5b44dbf5de918...|f88197465ea7920ad...|   delivered|     2017-11-18 19:28:06|2017-11-18 19:45:59|         2017-11-22 13:39:59|          2017-12-02 00:28:42|          2017-12-15 00:00:00|
|ad21c59c0840e6cb8...|8ab97904e6daea886...|   delivered|     2018-02-13 21:18:39|2018-02-13 22:20:29|         2018-02-14 19:46:34|          2018-02-16 18:17:02|          2018-02-26 00:00:00|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
only showing top 5 rows

In [6]:
# Quais são os possíveis status atribuídos a um pedido?

df_pedidos.groupBy("order_status").mean().orderBy("order_status").show()

+------------+
|order_status|
+------------+
|    approved|
|    canceled|
|     created|
|   delivered|
|    invoiced|
|  processing|
|     shipped|
| unavailable|
+------------+

In [7]:
# Quantos pedidos foram aprovados no ano de 2016?

df_pedidos.createOrReplaceTempView("view_pedidos")

df_t = spark.sql("""
SELECT COUNT(*) AS pedidos_aprovados_2017
FROM view_pedidos 
WHERE YEAR(order_approved_at)='2017'
""")

df_t.show()

+----------------------+
|pedidos_aprovados_2017|
+----------------------+
|                 44973|
+----------------------+

In [8]:
# Quais são os cinco maiores pedidos recebidos na plataforma? Identificar o meio de pagamento, valor, cidade e estado do cliente que realizou os respectivos pedidos.


# 1o Criando o dataframe com os dados de pagamento:
df_pagamento = spark\
  .read\
  .option("inferSchema", "true")\
  .option("header", "true")\
  .csv("/user/leandrocmleite/dataset_ecommerce/olist_order_payments_dataset.csv")

# 2o criando as tabelas para consulta SQL:
df_customers.createOrReplaceTempView("view_customer")
df_pagamento.createOrReplaceTempView("view_pagamento")

df_t = spark.sql("""
SELECT view_pedidos.customer_id, view_pagamento.payment_type, view_pagamento.payment_value, view_customer.customer_city, view_customer.customer_state FROM view_pagamento
INNER JOIN view_pedidos ON (view_pagamento.order_id = view_pedidos.order_id)
INNER JOIN view_customer ON (view_customer.customer_id = view_pedidos.customer_id) ORDER BY view_pagamento.payment_value DESC
LIMIT 5;
""")

df_t.show(5, truncate=False)

+--------------------------------+------------+-------------+--------------+--------------+
|customer_id                     |payment_type|payment_value|customer_city |customer_state|
+--------------------------------+------------+-------------+--------------+--------------+
|1617b1357756262bfa56ab541c47bc16|credit_card |13664.08     |rio de janeiro|RJ            |
|ec5b2ba62e574342386871631fafd3fc|boleto      |7274.88      |vila velha    |ES            |
|c6e2731c5b391845f6800c97401a43a9|credit_card |6929.31      |campo grande  |MS            |
|f48d464a0baaea338cb25f816991ab1f|boleto      |6922.21      |vitoria       |ES            |
|3fd6777bbce08a352fddd04e4a7cc8f6|boleto      |6726.66      |marilia       |SP            |
+--------------------------------+------------+-------------+--------------+--------------+

In [9]:
#Com base na resposta anterior, quais são os possíveis endereços para o cliente que realizou o maior pedido na plataforma?

# dataframe com os dados de endereços do Brasil:
df_brazil_zip = spark\
  .read\
  .option("inferSchema", "true")\
  .option("header", "true")\
  .csv("/user/leandrocmleite/dataset_ecommerce/brazil.csv")

# Tabela para consulta SQL com dados dos endereços:
df_brazil_zip.createOrReplaceTempView("view_brazil_zip")

df_t = spark.sql("""
SELECT DISTINCT view_brazil_zip.street, view_customer.customer_id, view_customer.customer_zip_code_prefix, view_brazil_zip.region, view_brazil_zip.postcode
FROM view_customer
INNER JOIN view_brazil_zip
ON view_brazil_zip.postcode LIKE CONCAT('%', SUBSTRING(view_customer.customer_zip_code_prefix,1,5),'%')
WHERE view_customer.customer_id = '1617b1357756262bfa56ab541c47bc16';
""")

df_t.show(25, truncate=False)

+--------------------------------+--------------------------------+------------------------+------+---------+
|street                          |customer_id                     |customer_zip_code_prefix|region|postcode |
+--------------------------------+--------------------------------+------------------------+------+---------+
|RUA  OLIMPIO PINHEIRO           |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-050|
|RUA  MAURICIO ZEHURI            |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-075|
|RUA  DJALMA LIMA                |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-020|
|RUA OPERARIO JOAO  BARROS       |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-050|
|RUA OPERARIO JOAO  BARROS       |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-000|
|RUA VEREADOR HELVAN GARCEZ      |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-050|
|RUA  OLIMPIO PINHEIRO           |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-125|
|RUA OPERARIO JOAO BARROS        |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-000|
|RUA VEREADOR HELVAN GARCEZ      |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-156|
|RUA  SEVERINO COUTINHO          |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-135|
|RUA  LUIS GRAIM                 |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-000|
|RUA  ARNALDO TELES DA FONSECA   |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-050|
|RUA  VITERICO BATISTA DE AZEVEDO|1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-046|
|RUA  CAMERINO                   |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-011|
|AVENIDA MARECHAL FLORIANO       |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-001|
|RUA  CAMERINO                   |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-010|
|TRAVESSA CORONEL JULIAO         |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-040|
|RUA  MONSENHOR ALVES ROCHA      |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-002|
|AVENIDA MARECHAL FLORIANO       |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-004|
|LADEIRA  DO PEDRO ANTONIO       |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-090|
|RUA  ALEXANDRE MACKENZIE        |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-002|
|RUA  DO ACRE                    |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-100|
|RUA  LEANDRO MARTINS            |1617b1357756262bfa56ab541c47bc16|20080                   |RJ    |20080-070|
+--------------------------------+--------------------------------+------------------------+------+---------+

<h4> Acrescentando uma nova análise ao trabalho realizado em Hadoop:</h4>
<h5><br>
Iremos a partir do dataframe de pagamentos (df_pagamentos) analisar alguns dados através do agrupamento da forma de pagamento utilizado em cada pedido e obter desta forma alguns insights com relação as valores, quantidade de parcelas, volumes de pedidos e valores totais relacionados a cado um dos meios de pagamentos utilizados na plataforma.
</h5>

In [10]:
df_pagamento.show(5)

+--------------------+------------------+------------+--------------------+-------------+
|            order_id|payment_sequential|payment_type|payment_installments|payment_value|
+--------------------+------------------+------------+--------------------+-------------+
|b81ef226f3fe1789b...|                 1| credit_card|                   8|        99.33|
|a9810da82917af2d9...|                 1| credit_card|                   1|        24.39|
|25e8ea4e93396b6fa...|                 1| credit_card|                   1|        65.71|
|ba78997921bbcdc13...|                 1| credit_card|                   8|       107.78|
|42fdf880ba16b47b5...|                 1| credit_card|                   2|       128.45|
+--------------------+------------------+------------+--------------------+-------------+
only showing top 5 rows

In [11]:
# Analisando os dados pelo agrupamento do tipo do meio de pagamento utilizado nos pedidos:
df_pagamento.groupBy('payment_type').sum().orderBy('sum(payment_sequential)',ascending=False).show()

+------------+-----------------------+-------------------------+--------------------+
|payment_type|sum(payment_sequential)|sum(payment_installments)|  sum(payment_value)|
+------------+-----------------------+-------------------------+--------------------+
| credit_card|                  77115|                   269332|1.2542084189999508E7|
|      boleto|                  19785|                    19784|  2869361.2699999996|
|     voucher|                  15029|                     5775|  379436.87000000046|
|  debit_card|                   1582|                     1529|  217989.79000000018|
| not_defined|                      3|                        3|                 0.0|
+------------+-----------------------+-------------------------+--------------------+

In [12]:
# Calculando a média de parcelas de acordo com o meio de pagamento utilizado:
df_pagamento.groupBy('payment_type').avg('payment_installments').orderBy('avg(payment_installments)',ascending=False).show()

+------------+-------------------------+
|payment_type|avg(payment_installments)|
+------------+-------------------------+
| credit_card|        3.507155413763917|
|      boleto|                      1.0|
|     voucher|                      1.0|
| not_defined|                      1.0|
|  debit_card|                      1.0|
+------------+-------------------------+

<h2>Parte 2:</h2>
<h5> Utilizar a biblioteca PySpark para treinar um modelo de aprendizado de máquina </h5>

<h5> Descrição do problema:
Desejamos prever a quantidade de parcelas que serão escolhidas pelo cliente quando utlizado o cartão de crédito como meio de pagamento. Para isso, utilizaremos uma base de dados com as seguintes informações:
    <ul>
    <li>Cliente ID -- customer_id </li>
    <li>Estado -- customer_state </li>
    <li>Cidade -- customer_city </li>
    <li>Prefixo do CEP do cliente -- customer_zip_code_prefix</li>
    <li> Tipo pagamaento realizado -- payment_type
    <li>Quantidade de parcelas -- payment_installments</li>
    <li>Valor da compra -- payment_value</li>
    </ul>

</h5>

In [13]:
# Obter o dataset com as informações necessárias referentes aos cadastro dos clientes, pedidos e meios de pagamento utilizado.

df_order_fin = spark.sql("""
SELECT view_pedidos.customer_id, view_customer.customer_state, view_customer.customer_city, view_customer.customer_zip_code_prefix, view_pagamento.payment_type, view_pagamento.payment_installments,view_pagamento.payment_value FROM view_pagamento
INNER JOIN view_pedidos ON (view_pagamento.order_id = view_pedidos.order_id)
INNER JOIN view_customer ON (view_customer.customer_id = view_pedidos.customer_id) ORDER BY view_pagamento.payment_value DESC;
""")

df_order_fin.show(5, truncate=False)

+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
|customer_id                     |customer_state|customer_city |customer_zip_code_prefix|payment_type|payment_installments|payment_value|
+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
|1617b1357756262bfa56ab541c47bc16|RJ            |rio de janeiro|20080                   |credit_card |1                   |13664.08     |
|ec5b2ba62e574342386871631fafd3fc|ES            |vila velha    |29102                   |boleto      |1                   |7274.88      |
|c6e2731c5b391845f6800c97401a43a9|MS            |campo grande  |79042                   |credit_card |8                   |6929.31      |
|f48d464a0baaea338cb25f816991ab1f|ES            |vitoria       |29066                   |boleto      |1                   |6922.21      |
|3fd6777bbce08a352fddd04e4a7cc8f6|SP            |marilia       |17506                   |boleto      |1                   |6726.66      |
+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
only showing top 5 rows

In [14]:
df_order_fin.count()

103886

<u> Manipular o dataframe anterior para trabalharmos com um novo dataframe que represente somente os pedidos pagos utilizando cartão de crédito. </u>

In [18]:
# A partit do dataframe anterir vamos selecionar somente os pedidos que utilizaram como meio de pagamento o cartão de crédito.

df_order_credcard = df_order_fin[df_order_fin['payment_type'] =='credit_card']
df_order_credcard.show(5, False)

+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
|customer_id                     |customer_state|customer_city |customer_zip_code_prefix|payment_type|payment_installments|payment_value|
+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
|1617b1357756262bfa56ab541c47bc16|RJ            |rio de janeiro|20080                   |credit_card |1                   |13664.08     |
|c6e2731c5b391845f6800c97401a43a9|MS            |campo grande  |79042                   |credit_card |8                   |6929.31      |
|df55c14d1476a9a3467f131269c2477f|RJ            |araruama      |28970                   |credit_card |10                  |4950.34      |
|e0a2412720e9ea4f26c1ac985f6a7358|GO            |goiania       |74210                   |credit_card |5                   |4809.44      |
|24bbf5fd2f2e1b359ee7de94defc4a15|SP            |maua          |9341                    |credit_card |8                   |4764.34      |
+--------------------------------+--------------+--------------+------------------------+------------+--------------------+-------------+
only showing top 5 rows

In [20]:
df_order_credcard.count()

76795

In [21]:
# Importar as bibliotecas e módulos necessários para trabalharmos com o modelo de regressão linear
import pyspark
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler, OneHotEncoder, StringIndexer
from pyspark.ml.regression import LinearRegression
from pyspark.ml.clustering import KMeans
from pyspark.ml.evaluation import ClusteringEvaluator

<u>Tratando os dados categóricos:</u>

In [22]:
# Transfor atributos categóricos em numéricos.
# Prefixo CEP tb é tratado como categoria.

state_index = StringIndexer(inputCol="customer_state", outputCol="state_Label")
model_state = state_index.fit(df_order_credcard)
df_order_credcard = model_state.transform(df_order_credcard)

city_index = StringIndexer(inputCol="customer_city", outputCol="city_Label")
model_city = city_index.fit(df_order_credcard)
df_order_credcard = model_city.transform(df_order_credcard)

#zip_index = StringIndexer(inputCol="customer_zip_code_prefix", outputCol="zip_Label")
#model_zip = zip_index.fit(df_order_credcard)
#df_order_credcard = model_zip.transform(df_order_credcard)

#customer_index = StringIndexer(inputCol="customer_id", outputCol="customer_Label")
#model_zip = customer_index.fit(df_order_credcard)
#df_order_credcard = model_zip.transform(df_order_credcard)

df_order_credcard.show(5)

+--------------------+--------------+--------------+------------------------+------------+--------------------+-------------+-----------+----------+
|         customer_id|customer_state| customer_city|customer_zip_code_prefix|payment_type|payment_installments|payment_value|state_Label|city_Label|
+--------------------+--------------+--------------+------------------------+------------+--------------------+-------------+-----------+----------+
|1617b1357756262bf...|            RJ|rio de janeiro|                   20080| credit_card|                   1|     13664.08|        1.0|       1.0|
|c6e2731c5b391845f...|            MS|  campo grande|                   79042| credit_card|                   8|      6929.31|       15.0|      39.0|
|df55c14d1476a9a34...|            RJ|      araruama|                   28970| credit_card|                  10|      4950.34|        1.0|     166.0|
|e0a2412720e9ea4f2...|            GO|       goiania|                   74210| credit_card|                   5|      4809.44|        9.0|      15.0|
|24bbf5fd2f2e1b359...|            SP|          maua|                    9341| credit_card|                   8|      4764.34|        0.0|      33.0|
+--------------------+--------------+--------------+------------------------+------------+--------------------+-------------+-----------+----------+
only showing top 5 rows

In [23]:
#encoder = OneHotEncoder(inputCols=["state_Label","city_Label","zip_Label"], outputCols=["state_vec","city_vec","zip_vec"], dropLast=True)
#encoder = OneHotEncoder(inputCols=["state_Label","city_Label","customer_Label"], outputCols=["state_vec","city_vec","customer_vec"], dropLast=True)

encoder = OneHotEncoder(inputCols=["state_Label","city_Label"], outputCols=["state_vec","city_vec"], dropLast=True)
model_encoder = encoder.fit(df_order_credcard)
df_order_credcard = model_encoder.transform(df_order_credcard)

In [25]:
#df_order_credcard.select(["payment_value","state_vec","city_vec","zip_vec"]).show(5)
#df_order_credcard.select(["payment_value","state_vec","city_vec","customer_vec"]).show(5)

df_order_credcard.select(["payment_value","state_vec","city_vec"]).show(5)

+-------------+---------------+------------------+
|payment_value|      state_vec|          city_vec|
+-------------+---------------+------------------+
|     13664.08| (26,[1],[1.0])|  (3743,[1],[1.0])|
|      6929.31|(26,[15],[1.0])| (3743,[39],[1.0])|
|      4950.34| (26,[1],[1.0])|(3743,[166],[1.0])|
|      4809.44| (26,[9],[1.0])| (3743,[15],[1.0])|
|      4764.34| (26,[0],[1.0])| (3743,[33],[1.0])|
+-------------+---------------+------------------+
only showing top 5 rows

<u>Criar a coluna com as features que serão utilizadas no modelo.</u>

In [26]:
#assembler = VectorAssembler(inputCols=["payment_value", "state_vec", "city_vec", "zip_vec"],outputCol="features")
#assembler = VectorAssembler(inputCols=["payment_value", "state_vec", "city_vec", "customer_vec"],outputCol="features")

assembler = VectorAssembler(inputCols=["payment_value", "state_vec", "city_vec"],outputCol="features")
df_features = assembler.transform(df_order_credcard)
df_features.select(["payment_installments", "features"]).show(5,truncate=False)

+--------------------+----------------------------------+
|payment_installments|features                          |
+--------------------+----------------------------------+
|1                   |(3770,[0,2,28],[13664.08,1.0,1.0])|
|8                   |(3770,[0,16,66],[6929.31,1.0,1.0])|
|10                  |(3770,[0,2,193],[4950.34,1.0,1.0])|
|5                   |(3770,[0,10,42],[4809.44,1.0,1.0])|
|8                   |(3770,[0,1,60],[4764.34,1.0,1.0]) |
+--------------------+----------------------------------+
only showing top 5 rows

In [50]:
df_features.dropDuplicates(['payment_installments']).select('payment_installments').orderBy('payment_installments',ascending=True).show(50)

+--------------------+
|payment_installments|
+--------------------+
|                   0|
|                   1|
|                   2|
|                   3|
|                   4|
|                   5|
|                   6|
|                   7|
|                   8|
|                   9|
|                  10|
|                  11|
|                  12|
|                  13|
|                  14|
|                  15|
|                  16|
|                  17|
|                  18|
|                  20|
|                  21|
|                  22|
|                  23|
|                  24|
+--------------------+

<u>Criar um novo dataframe somente com os dados que serão utilizados no modelo de aprendizagem:</u>

In [51]:
df_novo = df_features.select(["payment_installments", "features"]).withColumnRenamed("payment_installments","label")
df_novo.show(5,truncate=False)

+-----+----------------------------------+
|label|features                          |
+-----+----------------------------------+
|1    |(3770,[0,2,28],[13664.08,1.0,1.0])|
|8    |(3770,[0,16,66],[6929.31,1.0,1.0])|
|10   |(3770,[0,2,193],[4950.34,1.0,1.0])|
|5    |(3770,[0,10,42],[4809.44,1.0,1.0])|
|8    |(3770,[0,1,60],[4764.34,1.0,1.0]) |
+-----+----------------------------------+
only showing top 5 rows

In [52]:
df_novo.printSchema()

root
 |-- label: integer (nullable = true)
 |-- features: vector (nullable = true)

<u> Dividindo a base em conjuntos de treino e teste:</u>

In [53]:
(trainingData, testData) = df_novo.randomSplit([0.8,0.2])
print(trainingData.count(), testData.count())

61408 15387

In [54]:
model = LinearRegression().fit(trainingData)
df_result = model.transform(testData)
df_result.show(50,False)

23/10/08 12:28:50 WARN Instrumentation: [dc24ef38] regParam is zero, which might cause numerical instability and overfitting.
23/10/08 12:28:52 WARN Instrumentation: [dc24ef38] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

+-----+-------------------------------+------------------+
|label|features                       |prediction        |
+-----+-------------------------------+------------------+
|1    |(3770,[0,1,27],[0.31,1.0,1.0]) |2.311660760348539 |
|1    |(3770,[0,1,27],[0.33,1.0,1.0]) |2.311755275814942 |
|1    |(3770,[0,1,27],[0.8,1.0,1.0])  |2.3139763892754046|
|1    |(3770,[0,1,27],[0.84,1.0,1.0]) |2.31416542020821  |
|1    |(3770,[0,1,27],[1.02,1.0,1.0]) |2.315016059405834 |
|1    |(3770,[0,1,27],[1.74,1.0,1.0]) |2.3184186161963303|
|1    |(3770,[0,1,27],[2.74,1.0,1.0]) |2.323144389516464 |
|1    |(3770,[0,1,27],[3.14,1.0,1.0]) |2.3250346988445174|
|1    |(3770,[0,1,27],[3.86,1.0,1.0]) |2.3284372556350137|
|1    |(3770,[0,1,27],[6.72,1.0,1.0]) |2.341952967330596 |
|1    |(3770,[0,1,27],[6.9,1.0,1.0])  |2.34280360652822  |
|1    |(3770,[0,1,27],[8.45,1.0,1.0]) |2.350128555174427 |
|1    |(3770,[0,1,27],[8.45,1.0,1.0]) |2.350128555174427 |
|1    |(3770,[0,1,27],[8.78,1.0,1.0]) |2.3516880603700714|
|1    |(3770,[0,1,27],[9.89,1.0,1.0]) |2.3569336687554197|
|1    |(3770,[0,1,27],[10.07,1.0,1.0])|2.3577843079530436|
|1    |(3770,[0,1,27],[10.71,1.0,1.0])|2.3608088028779295|
|1    |(3770,[0,1,27],[12.99,1.0,1.0])|2.371583566047834 |
|1    |(3770,[0,1,27],[13.87,1.0,1.0])|2.3757422465695517|
|1    |(3770,[0,1,27],[14.2,1.0,1.0]) |2.377301751765196 |
|1    |(3770,[0,1,27],[14.29,1.0,1.0])|2.3777270713640077|
|1    |(3770,[0,1,27],[14.47,1.0,1.0])|2.378577710561632 |
|1    |(3770,[0,1,27],[14.65,1.0,1.0])|2.379428349759256 |
|1    |(3770,[0,1,27],[14.69,1.0,1.0])|2.3796173806920615|
|1    |(3770,[0,1,27],[15.85,1.0,1.0])|2.3850992777434166|
|1    |(3770,[0,1,27],[16.29,1.0,1.0])|2.3871786180042753|
|1    |(3770,[0,1,27],[16.29,1.0,1.0])|2.3871786180042753|
|1    |(3770,[0,1,27],[16.29,1.0,1.0])|2.3871786180042753|
|1    |(3770,[0,1,27],[16.75,1.0,1.0])|2.389352473731537 |
|1    |(3770,[0,1,27],[17.29,1.0,1.0])|2.391904391324409 |
|1    |(3770,[0,1,27],[17.38,1.0,1.0])|2.392329710923221 |
|1    |(3770,[0,1,27],[18.28,1.0,1.0])|2.396582906911341 |
|1    |(3770,[0,1,27],[18.38,1.0,1.0])|2.3970554842433547|
|1    |(3770,[0,1,27],[18.61,1.0,1.0])|2.3981424121069854|
|1    |(3770,[0,1,27],[18.67,1.0,1.0])|2.3984259585061936|
|1    |(3770,[0,1,27],[18.87,1.0,1.0])|2.3993711131702202|
|1    |(3770,[0,1,27],[18.87,1.0,1.0])|2.3993711131702202|
|1    |(3770,[0,1,27],[18.87,1.0,1.0])|2.3993711131702202|
|1    |(3770,[0,1,27],[19.07,1.0,1.0])|2.400316267834247 |
|1    |(3770,[0,1,27],[19.33,1.0,1.0])|2.4015449688974817|
|1    |(3770,[0,1,27],[19.59,1.0,1.0])|2.4027736699607165|
|1    |(3770,[0,1,27],[19.78,1.0,1.0])|2.403671566891542 |
|1    |(3770,[0,1,27],[19.88,1.0,1.0])|2.4041441442235554|
|1    |(3770,[0,1,27],[20.03,1.0,1.0])|2.4048530102215753|
|1    |(3770,[0,1,27],[20.03,1.0,1.0])|2.4048530102215753|
|1    |(3770,[0,1,27],[20.03,1.0,1.0])|2.4048530102215753|
|1    |(3770,[0,1,27],[20.04,1.0,1.0])|2.4049002679547766|
|1    |(3770,[0,1,27],[20.27,1.0,1.0])|2.4059871958184074|
|1    |(3770,[0,1,27],[20.29,1.0,1.0])|2.40608171128481  |
|1    |(3770,[0,1,27],[20.29,1.0,1.0])|2.40608171128481  |
+-----+-------------------------------+------------------+
only showing top 50 rows

In [55]:
#print(model.coefficients)
print(model.intercept)
print(model.summary.meanSquaredError)
print(model.summary.rootMeanSquaredError)
print(model.summary.r2)

2.5673689447744
6.502354413091804
2.5499714533876263
0.20279041277756193

<hr>
<h4>Conclusão e Melhorias:</h4>
O modelo de aprendizado baseado nos algoritmos de regressão linear para predizer a quantidade de parcelas escolhidas no momento da compra com base nas caracterísitcas dos dados demográficos de localização do cliente (estado e cidade) e valor da compra, não apresentou um resultado satisfatório com base nas margens de erro observadas.
Um sugestão futura para melhor tratamento para deste tipo de problema seja a utilização de outros modelos matemáticos, incluindo o aprendizado baseado no agrupamento de dados, que possibilitem uma melhor taxa de assertividade no que diz respeito a quantidade de parcelas escolhidas pelos clientes no momento da compra, incluindo aí outros dados relevantes que possam influenciar nessa escolha, como dia do mês, por exemplo.